apiVersion: v1
kind: Service
metadata:
  name: hello-node
  labels:
    app: nodejs
spec:
  selector:
    app: nodejs
  type: NodePort
  ports:
    - protocol: TCP
      port: 12321
      targetPort: 8080
