apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: hello-hello:v1
          ports:
          - containerPort: 8080 # exposed port

